import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const myRobotoFont = localFont({
  src: [
    {
      path: "./Roboto-Regular.ttf",
    },
    {
      path: "./Roboto-Bold.ttf",
    },
  ],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${myRobotoFont.className}`}>{children}</body>
    </html>
  );
}
